version: "3.9"

services:
  app:
    container_name: app
    build:
        context: .
        dockerfile: Dockerfile
    environment:
        ConnectionStrings__DefaultConnection: "Host=db;Database=drivee_db;Username=admin;Password=admin"
    ports:
        - "8080:8080"
    depends_on:
        - db
  db:
    container_name: db
    image: postgres:16
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: drivee_db
    ports:
        - "5432:5432"
    volumes:
        - pgdata:/var/lib/postgresql/data
volumes:
    pgdata: {}